### ISSUE TITLE
Unable to customize HTTP status code when validating response data

### ISSUE THREAD

**Issue by twelvelabs** [kemingy/flaskerk#35]
I'm trying out `flaskerk` and attempting to define an endpoint that creates a resource and returns a [HTTP 201 Created](https://restfulapi.net/http-status-201-created/) response. I typically return the newly created resource in the response body for those types of endpoints.

It looks like the current implementation supports customizing the successful response code by raising an `HTTPException` with a 2xx code, but this doesn't appear to work in combination with a response schema (I think this was raised in #26). It's also a little unintuitive to me to use exceptions as a way of signaling a successful action. Would you be open to a PR that added an optional `resp_code` (or perhaps `status`... whatever you prefer) kwarg to the validate decorator? Something like so:

```python
@app.route("/users", methods=["POST"])
@api.validate(data=User, resp=User, resp_code=201)
def create_user():
    # create the user...
    return user, 201
```

**Comment by kemingy** [comment]
Thanks for your feedback. I found this issue when I was trying to get a structured error message with JSON format. It turns out every response may have a JSON body.

You are right, people may get confused about the interface. I really should think more about the design part before coding. (this library is still a semi-finished product)

Currently, I'm working on a new library [spectree](https://github.com/0b01001001/spectree) that supports `flask`, `falcon`, `starlette`. As shown in [spectree #1](https://github.com/0b01001001/spectree/issues/1), there will be a new interface and I think that can solve this problem. The new library should support everything that this library has. I'm working on the documents and tests part of it. Would you like to give it a try(you may check the [examples](https://github.com/0b01001001/spectree/tree/master/examples) part first)?

**Comment by kemingy** [comment]
Hi @twelvelabs , I just add tests and docs for [spectree](https://github.com/0b01001001/spectree). Fell free to give it a try.

**Comment by twelvelabs** [comment]
I'm checking it out now. I really like the new `validate` interface w/ the explicit `Response` config.

Closing this issue since it seems that `spectree` will be the supported library from now on.
